### PR TITLE
benchmarks for  `get` on different database sizes & initial benchmarks for `iter`

### PR DESCRIPTION
**Pull request by snd**
moved keeping track of benchmarks to separate issue https://github.com/paritytech/paritydb/issues/55

### CODE REVIEW

**Comment by tomusdrw** [comment]
Should we run benchmarks on travis? (or at least compile them to make sure they don't get obsolete?)

**Comment by snd** [comment]
@tomusdrw i think we should. that way regressions are visible. even better would be some CI that automatically warns on regressions in PRs. i'll look into that

**Comment by snd** [comment]
this is blocked by https://github.com/paritytech/primitives/issues/6

see: https://travis-ci.org/paritytech/paritydb/jobs/311252023#L758

any help on that issue would be greatly appreciated!

**Comment by snd** [comment]
done

**Pull request merged**
